// Code generated by lungo 1.87.0 from Lean 4.34.1 for program tagged_urn_formal; DO NOT EDIT.

// Package formal calls the Lean program tagged_urn_formal (generated by lungo).
package formal

/*
#cgo CFLAGS: -I${SRCDIR}
#include <stdlib.h>
#include "tagged_urn_formal_program.h"

static int32_t tagged_urn_formal_go_call(lungo_entry f, const uint8_t *in, size_t n, lungo_buffer *out) { return f(in, n, out); }
*/
import "C"

import (
	"math/big"
	"sync"
	"unsafe"

	lungo "github.com/machinefabric/lungo-go"
)

// Generated for exactly this version of the support module.
const _ = lungo.EnforceVersion1_87_0

var programOnce sync.Once
var theProgram *lungo.Program

func program() *lungo.Program {
	programOnce.Do(func() { theProgram = lungo.NewProgram(unsafe.Pointer(C.tagged_urn_formal__types())) })
	return theProgram
}

func call(entry C.lungo_entry, in []byte) (int32, []byte) {
	var buf C.lungo_buffer
	var p *C.uint8_t
	if len(in) > 0 {
		p = (*C.uint8_t)(unsafe.Pointer(&in[0]))
	}
	status := C.tagged_urn_formal_go_call(entry, p, C.size_t(len(in)), &buf)
	var out []byte
	if buf.len > 0 {
		out = C.GoBytes(unsafe.Pointer(buf.data), C.int(buf.len))
	}
	C.lungo_buffer_free(&buf)
	return int32(status), out
}

// Wf is Lean's TaggedUrn.Exec.Wf, held by handle: only the program's functions make and read its values.
type Wf struct{ lungo.Opaque }

// WfFingerprint is the layout fingerprint of Lean's TaggedUrn.Exec.Wf: a package using Wf from this one checks it.
const WfFingerprint = "20e9f81ad195b2f4a481e7a5dcae2b3d0de6efe7b3dc720db0e2aa3b52527785"

type wfDescriptor struct{}

// WfType describes TaggedUrn.Exec.Wf for polymorphic functions.
func WfType() lungo.Type[Wf] { return wfDescriptor{} }

func (wfDescriptor) Expr() []byte { return lungo.InductiveExpr(0) }
func (wfDescriptor) Encode(w *lungo.Writer, v Wf) error {
	return lungo.OpaqueType.Encode(w, v.Opaque)
}
func (wfDescriptor) Decode(r *lungo.Reader) (Wf, error) {
	o, err := lungo.OpaqueType.Decode(r)
	return Wf{o}, err
}

// Constraint is Lean's TaggedUrn.Constraint: one of ConstraintMissing, ConstraintUnconstrained, ConstraintOptionalNot, ConstraintPresent, ConstraintPresentNot, ConstraintExact, ConstraintAbsent.
type Constraint interface{ isConstraint() }

// ConstraintMissing is Lean's TaggedUrn.Constraint.missing.
type ConstraintMissing struct{}

func (ConstraintMissing) isConstraint() {}

// ConstraintUnconstrained is Lean's TaggedUrn.Constraint.unconstrained.
type ConstraintUnconstrained struct{}

func (ConstraintUnconstrained) isConstraint() {}

// ConstraintOptionalNot is Lean's TaggedUrn.Constraint.optionalNot.
type ConstraintOptionalNot struct {
	Value string
}

func (ConstraintOptionalNot) isConstraint() {}

// ConstraintPresent is Lean's TaggedUrn.Constraint.present.
type ConstraintPresent struct{}

func (ConstraintPresent) isConstraint() {}

// ConstraintPresentNot is Lean's TaggedUrn.Constraint.presentNot.
type ConstraintPresentNot struct {
	Value string
}

func (ConstraintPresentNot) isConstraint() {}

// ConstraintExact is Lean's TaggedUrn.Constraint.exact.
type ConstraintExact struct {
	Value string
}

func (ConstraintExact) isConstraint() {}

// ConstraintAbsent is Lean's TaggedUrn.Constraint.absent.
type ConstraintAbsent struct{}

func (ConstraintAbsent) isConstraint() {}

// ConstraintFingerprint is the layout fingerprint of Lean's TaggedUrn.Constraint: a package using Constraint from this one checks it.
const ConstraintFingerprint = "481fc09e23c6415a7c3f05887577ec940a6ecc84b005e63476c1060b59edcac7"

type constraintDescriptor struct{}

// ConstraintType describes TaggedUrn.Constraint for polymorphic functions.
func ConstraintType() lungo.Type[Constraint] {
	return constraintDescriptor{}
}

func (t constraintDescriptor) Expr() []byte { return lungo.InductiveExpr(1) }

func (t constraintDescriptor) Encode(w *lungo.Writer, v Constraint) error {
	switch x := v.(type) {
	case ConstraintMissing:
		w.U32(0)
		return nil
	case *ConstraintMissing:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintMissing")
		}
		return t.Encode(w, *x)
	case ConstraintUnconstrained:
		w.U32(1)
		return nil
	case *ConstraintUnconstrained:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintUnconstrained")
		}
		return t.Encode(w, *x)
	case ConstraintOptionalNot:
		w.U32(2)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintOptionalNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintOptionalNot")
		}
		return t.Encode(w, *x)
	case ConstraintPresent:
		w.U32(3)
		return nil
	case *ConstraintPresent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresent")
		}
		return t.Encode(w, *x)
	case ConstraintPresentNot:
		w.U32(4)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintPresentNot:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintPresentNot")
		}
		return t.Encode(w, *x)
	case ConstraintExact:
		w.U32(5)
		if err := lungo.StringType.Encode(w, x.Value); err != nil {
			return err
		}
		return nil
	case *ConstraintExact:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintExact")
		}
		return t.Encode(w, *x)
	case ConstraintAbsent:
		w.U32(6)
		return nil
	case *ConstraintAbsent:
		if x == nil {
			return lungo.Malformed("a nil *ConstraintAbsent")
		}
		return t.Encode(w, *x)
	}
	return lungo.Malformed("a nil Constraint")
}

func (t constraintDescriptor) Decode(r *lungo.Reader) (Constraint, error) {
	c, err := r.U32()
	if err != nil {
		return nil, err
	}
	switch c {
	case 0:
		var v ConstraintMissing
		return v, nil
	case 1:
		var v ConstraintUnconstrained
		return v, nil
	case 2:
		var v ConstraintOptionalNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 3:
		var v ConstraintPresent
		return v, nil
	case 4:
		var v ConstraintPresentNot
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 5:
		var v ConstraintExact
		f0, err := lungo.StringType.Decode(r)
		if err != nil {
			return nil, err
		}
		v.Value = f0
		return v, nil
	case 6:
		var v ConstraintAbsent
		return v, nil
	}
	return nil, lungo.Malformed("constructor index %d of TaggedUrn.Constraint", c)
}

// Comparable is Lean's TaggedUrn.Exec.comparable : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func Comparable(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dcomparable), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Equivalent is Lean's TaggedUrn.Exec.equivalent : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func Equivalent(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dequivalent), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Make is Lean's TaggedUrn.Exec.make : String → List (String × TaggedUrn.Constraint) → Option TaggedUrn.Exec.Wf
func Make(scheme string, tags []lungo.Pair[string, Constraint]) (result lungo.Option[Wf], err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = lungo.StringType.Encode(w, scheme); err != nil {
		return
	}
	if err = lungo.ListType(lungo.PairType(lungo.StringType, ConstraintType())).Encode(w, tags); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dmake), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.OptionType(WfType()))
}

// Meets is Lean's TaggedUrn.Exec.meets : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func Meets(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dmeets), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// MeetsClosed is Lean's TaggedUrn.Exec.meetsClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func MeetsClosed(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dmeetsClosed), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Refines is Lean's TaggedUrn.Exec.refines : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func Refines(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_drefines), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// RefinesClosed is Lean's TaggedUrn.Exec.refinesClosed : TaggedUrn.Exec.Wf → TaggedUrn.Exec.Wf → Bool
func RefinesClosed(a Wf, b Wf) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	if err = WfType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_drefinesClosed), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// Specificity is Lean's TaggedUrn.Exec.specificity : TaggedUrn.Exec.Wf → Nat
func Specificity(a Wf) (result *big.Int, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = WfType().Encode(w, a); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dspecificity), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.NatType)
}

// ValuesMatch is Lean's TaggedUrn.Exec.valuesMatch : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool
func ValuesMatch(inst Constraint, patt Constraint) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = ConstraintType().Encode(w, inst); err != nil {
		return
	}
	if err = ConstraintType().Encode(w, patt); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatch), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// ValuesMatchClosed is Lean's TaggedUrn.Exec.valuesMatchClosed : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool
func ValuesMatchClosed(inst Constraint, patt Constraint) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = ConstraintType().Encode(w, inst); err != nil {
		return
	}
	if err = ConstraintType().Encode(w, patt); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMatchClosed), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}

// ValuesMeet is Lean's TaggedUrn.Exec.valuesMeet : TaggedUrn.Constraint → TaggedUrn.Constraint → Bool
func ValuesMeet(a Constraint, b Constraint) (result bool, err error) {
	w := lungo.NewCall(program())
	defer w.Release()
	if err = ConstraintType().Encode(w, a); err != nil {
		return
	}
	if err = ConstraintType().Encode(w, b); err != nil {
		return
	}
	status, out := call(C.lungo_entry(C.tagged_urn_formal__call_l_TaggedUrn_dExec_dvaluesMeet), w.Bytes())
	return lungo.DecodeValue(program(), status, out, lungo.BoolType)
}
